---
- name: install domain service
  win_feature:
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: win domain
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: result
- debug:
    var: result

- win_reboot:
  when: result.reboot_required == true

- win_shell: nltest /dclist:"{{ ad_domain_name }}" 
  register: list

- debug: 
   var: list


# tasks file for win_ad_install
